### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by pckopat** [archielite/notification-plus#7]
Hello, I installed the plugin, but when I activate it, I encounter the following problem. How can I update the Core version?

Plugin Notification Plus requires 7.0.0 version of core, but your core version is 6.10.4. Please upgrade your core to use this plugin!

**Comment by dinhquochan** [comment]
Hi @pckopat, what is your script?

**Comment by pckopat** [comment]
nest  => https://nest.botble.com/

**Comment by dinhquochan** [comment]
Hi, 

Nest and other Botble products will be upgraded the core to version 7 soon, please wait.

**Comment by pckopat** [comment]
Approximately when will the update be released?

**Comment by sangnguyenplus** [comment]
@pckopat It's released. Just upgrade to the latest version of Nest, then you can use this plugin.

**Comment by pckopat** [comment]
@sangnguyenplus thanks.
